---
- hosts: webservers
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Install MySQL server
      apt:
        name: mariadb-server
        state: present

    - name: Install PHP and PHP-FPM
      apt:
        name:
          - php
          - php-fpm
          - php-mysql
        state: present

    - name: Start and enable Nginx
      systemd:
        name: nginx
        state: started
        enabled: yes

    - name: Start and enable MariaDB
      systemd:
        name: mariadb
        state: started
        enabled: yes
